### ISSUE TITLE
pre-alpha access please

### ISSUE THREAD

**Issue by ebrigham** [jducoeur/Querki#2]
Justin/Mark,
I can't be more thrilled about the idea of Querki and am glad that you're building it. It's baffling to me how much of the world still revolves around essentially small lists maintained/calculated by individuals in a spreadsheet somewhere (at least now more people use online spreadsheets). However, your solution with Querki is pretty much exactly the solution that I have been wanting. Furthermore, your choice of stack (ie: Scala through-and-through) is fantastic! I actually stumbled on your project as I was researching some ScalaJS stuff.

Could you please private message me instructions for how to join your alpha program? I would very much like to contribute.

P.S. Sorry for opening this random issue on Github, but it wasn't very clear to me how to contact you otherwise.

**Comment by jducoeur** [comment]
Heh -- quite all right.  I should put some contact info somewhere around here.  I'll PM you...

**Comment by jducoeur** [comment]
Hmm.  Actually, I'm not seeing how PM works in here.  (I'm still a bit of a GitHub naif, I'm afraid.)  Drop me an email at this username at gmail, and we can talk...

**Comment by jducoeur** [comment]
Closing this issue as general cleanup.  You're on the list -- expect an invitation before the end of March...
